# Tell Travis to use the Node 10.13 because node-gyp hates Node 11
language: node_js
node_js:
  - "10.13"

# Cache the node_modules directory between builds instead of re-compiling the whole directory each time you commit.
cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    secure: 2rxlYio6MqFRL4WKkVn6DkoSWPn9THh8D2+xhxoAmUm5pYJIiz5UYVlDOGpy0Hr3TYyrUlVIlrAJsOOOeX69xF29NoWXZCe3Ru7mgpCyvrd195WdbxU0qO9nDMXC8Y9Fa1W/ZOO2rRL8SatoBUxNieoh/qb5HhgX8xA45a3OlLNYQFpLPWqCqzzQJzZGt4/xMGNwAViyM6xm5lezz4I6gOAAk4hS7XeZcTABiLEmu3yK3rFrcYD/WA3u5yDnSfaRzZAORaZ3gKQvl0EBgbJEfP5qvneBkvPS3q7jLeX05q3jwNB7y1/PxANy1/anQqD7RHcmBM1k8dcdvdmudgOAhXR/1KLvShUDAHVIrvBMgPcpioQaD0GpQmYXk7ckCYqe3b8zHvJMSfHuavCgnJHz+bjdwGNOd3Ipom1cym4ii7F+t7xtf9L5ucdZpAO7AR5GUUHZ3Rmz/i5RtlyFEBVSfgRbEwkK1YAorTI665+uLoYZ82q6A49wlFBvhXuTzDilrREKzVoFGE2n4aY8kH0F0s2txHcDxF9/tqOGZcR5d8BBWdSCuyKmAGNqG/6TkmmmBq0nQf8E1Ssz7NlEHrDucmiEBfB2NB6e6asAd6hGZpiUEbdkYFaLVKFwq7cwee+C4Fu7DgkP1fIwtLvDVZMlapQe48mrGlKZi0VqMGvZW/U=

# Decrypt the keystore file and make sure we have the latest version of yarn. 
# Updated from npm update as because npm breaks dependencies
before_install:
  - openssl aes-256-cbc -k "$super_secret_password" -in healthdeck-droid.jks.enc -out healthdeck-droid.jks -d
  - yarn upgrade

# Tells Travis which commands to run. Commands run in a succession, and if a command fails (i.e. exits with anything but 0), 
# the build is marked as failed. Failed builds do not get deployed. Note that Travis knows to npm install already.

script:
  # Linting is disabled for now
  # - yarn lint
  
  # Run the test suites. -u updates snapshots, --coverage runs the automated Enzyme coverage tests.
  - yarn test -u --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# This is using Jay's encrypted Github API token, which has full access to the repo.
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: Rf3WKYGZ4I+JWn46jl6FIOO2R8Q2IBKm456+4dxXDuJNKGILL6XTRW4krY14tbf5rC1I/sWzI/Nk1n9s52zjhkeoVR8Q3WHjS/QG164B86pjgWJ18cDEPijA2cClR2kZub8fP4jpUaNkW9MD48A3h7xbfO3CjtG9HglaSGplzeZuyyEZCEFTXLbvppirv3zjgg8TVP2wnqMSxSxaNTVRhbu7RMkOcEdkUvvuQb8bDnrQKUKrJs9t1UIsHhOhFjOdEcNb5ErFilNKzmQZ2Xg5PTeYUaWYNNwnDNRbDMm8D/p4t5/0GDtLm4jO53mdeeOeHDc96iIU+dVAYLuflij9ORTcRNIe1jhwYfQNxRbND6hVgDCzcNJzU0goU8kLm5eWcFqJNjGIkp4EBGLaXwrcZ6fQsvv4YKx0Mg12zRyrFWUqGdvuBKGFmOHT12s4LOJsWLFBoW2hnh7yXfLi5fpTNywDuh+nelb/Kd3zjX9E4Day2Y0q1w+Kcb1Ec/GC4EqZ1rqUnaVZ5cYG9xRZdC0de8mogBHshgOfdym5jGt/HV5HPlTBf2WPIdKSiNZTYm6AFuknVlaJry/eSTeJUin5Xn+sVkBjVFWHSVo7oIYugC0wGmb6JhNQBZ0m9Mgbp/zzb2JSXCmcyZ2sX7/qAOFU6LFIw8i+XX6OHgOgNkGED08=
  file_glob: true
  file: /home/travis/build/UniversityOfSaskatchewanCMPT371/term-project-team-1/app/build/outputs/apk/release/*
  on:
    tags: true
    repo: UniversityOfSaskatchewanCMPT371/term-project-team-1