# Tell Travis to use the latest (stable) version of NodeJS
language: node_js
node_js:
  - "stable"

# Cache the node_modules directory between builds instead of re-compiling the whole directory each time you commit.
cache:
  directories:
    - node_modules

branches:
  only:
    - master

env:
  - CXX=g++-4.8
services:
  - mongodb 


before_install:
  - npm update

# Install npm dependencies. Internet says this is automatic, but I put it here just in case.
install:
  - npm install
  - npm install coveralls --save-dev


# Workaround to MongoDB locking out when sleep 15 is not implemented
# Will be uncommented when coverage testing is implemented
# before_script:
#   - sleep 15
#   - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

# Tells Travis which commands to run. Commands run in a succession, and if a command fails (i.e. exits with anything but 0), 
# the build is marked as failed. Failed builds do not get deployed. Note that Travis knows to npm install already.
script:
  # Linting is disabled for now until we find out how to style our shit
  # - npm run lint

  - npm test
  # Fuck coveralls man
  # Add { "coveralls": "jest --coverage | coveralls" } to package.json when I get this shit to work
  - npm run coveralls