# Tell Travis to use the Node 10.13 because node-gyp hates Node 11
language: node_js
node_js:
  - "10.13"

# Cache the node_modules directory between builds instead of re-compiling the whole directory each time you commit.
cache:
  yarn: true
  directories:
    - node_modules

# Decrypt the keystore file and make sure we have the latest version of yarn. 
# Updated from npm update as because npm breaks dependencies
before_install:
  - openssl aes-256-cbc -K $encrypted_40d199f203aa_key -iv $encrypted_40d199f203aa_iv
    -in healthdeck-droid.jks.enc -out healthdeck-droid.jks -d
  - yarn upgrade

# Tells Travis which commands to run. Commands run in a succession, and if a command fails (i.e. exits with anything but 0), 
# the build is marked as failed. Failed builds do not get deployed. Note that Travis knows to npm install already.

script:
  # Linting is disabled for now
  # - yarn lint
  
  # Run the test suites. -u updates snapshots, --coverage runs the automated Enzyme coverage tests.
  - yarn test -u --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# This is using Jay's encrypted Github API token, which has full access to the repo.
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: 
    secure: affe6a50e9582316b672ad8ed5bc3043d6920338
  file_glob: true
  file: /home/travis/build/UniversityOfSaskatchewanCMPT371/term-project-team-1/app/build/outputs/apk/release/*
  on:
    tags: true
   