sudo: false
language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  
script:
  - npm run lint
  - npm test